stages:
  - lint
  - test
  - build
  - release

image: python:3.11

pre-commit:
  stage: lint
  script:
    - pip install pre-commit
    - pre-commit run -av

test:
  stage: test
  script:
    - pip install pytest .[full]
    - pytest

build:
  stage: build
  image: quay.io/pypa/manylinux2014_x86_64
  script:
    - /opt/python/cp311-cp311/bin/pip install cibuildwheel
    - /opt/python/cp311-cp311/bin/python -m cibuildwheel --output-dir dist
  needs:
    - pre-commit
    # - test
  artifacts:
    paths:
      - dist/*

release:
  stage: release
  script:
    - pip install twine
    - twine upload dist/* --non-interactive --verbose
  needs:
    - build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $TWINE_PASSWORD
