stages:
  - lint
  - test
  - build
  - release

image: python:3.11

pre-commit:
  stage: lint
  script:
    - pip install pre-commit
    - pre-commit run -av

test:
  stage: test
  script:
    - pip install pytest .[full]
    - pytest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - apk add --no-cache python3 py3-venv
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install cibuildwheel
    - cibuildwheel --output-dir dist
  needs:
    - pre-commit
    # - test
  artifacts:
    paths:
      - dist/*

release:
  stage: release
  script:
    - pip install twine
    - twine upload dist/*.tar.gz --non-interactive --verbose
    - twine upload dist/*.whl --non-interactive --verbose
  needs:
    - build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $TWINE_PASSWORD
