stages:
  - lint
  - test
  - build
  - release

include:
  - project: tac_tech/ci-templates
    file: /defaults.yml
  - project: tac_tech/ci-templates
    file: /lint/pre-commit.yml
  - project: tac_tech/ci-templates
    file: /test/default.yml
  - project: tac_tech/ci-templates
    file: /build/default.yml
  - project: tac_tech/ci-templates
    file: /release/default.yml
