config:
  seed:
    dest:
      positional: true
      help: The base directory to copy the files to
      cli: True
    overwrite:
      action: store_true
      default: false
      help: Overwrite conflicting files
      cli: True
    test:
      action: store_true
      default: false
      help: Don't copy the files for real
      cli: True
    src:
      choices: templates
      default: plugin
      help: The seed template to use
      cli: True
    args:
      help: Any key=value pairs to pass on to the jinja renderer
      default: []
      positional: True
      nargs: "..."
      cli: True
dyne:
  seed:
    - seed
  template:
    - template

import:
  - concurrent.futures
  - copier
  - functools
